export const myVideos = [
  {
    videoId: "7wnove7K-ZQ",
    title: "Introduction to Programming & Python | Python Tutorial - Day #1",
    thumbnailUrl: "https://i.ytimg.com/vi/7wnove7K-ZQ/hqdefault.jpg",
    description:
      "This video serves as the first day of the Python tutorial series, introducing viewers to programming concepts and Python basics.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 1500000,
    likes: 25000,
    dislikes: 100,
    uploadDate: "2022-01-01",
    category: "Education",
    comments: [
      {
        username: "learner101",
        userId: "user001",
        text: "This tutorial made Python so easy to understand. Thank you!",
        timestamp: "2022-01-02T10:00:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=7wnove7K-ZQ",
  },
  {
    videoId: "BsDoLVMnmZs",
    title: "HTML Tutorial For Beginners In Hindi (With Notes)",
    thumbnailUrl: "https://i.ytimg.com/vi/BsDoLVMnmZs/hqdefault.jpg",
    description:
      "A comprehensive HTML tutorial designed for beginners, complete with notes to aid learning.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 2000000,
    likes: 30000,
    dislikes: 200,
    uploadDate: "2021-12-15",
    category: "Education",
    comments: [
      {
        username: "webdev_newbie",
        userId: "user002",
        text: "This HTML tutorial is exactly what I needed. Great explanations!",
        timestamp: "2021-12-16T08:30:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=BsDoLVMnmZs",
  },
  {
    videoId: "vxHUFFiT0OI",
    title: "The Ultimate Python Crash Course Featuring Code With Harry",
    thumbnailUrl: "https://i.ytimg.com/vi/vxHUFFiT0OI/hqdefault.jpg",
    description:
      "A beginner-friendly introduction to Python, featuring hands-on examples and practical applications.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 1800000,
    likes: 22000,
    dislikes: 150,
    uploadDate: "2021-11-20",
    category: "Education",
    comments: [
      {
        username: "python_dev",
        userId: "user003",
        text: "This crash course is a gem for beginners. Thanks, Harry!",
        timestamp: "2021-11-21T12:45:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=vxHUFFiT0OI",
  },
  {
    videoId: "IwlMBvuDk5E",
    title: "Web Development Tutorial from Code With Harry",
    thumbnailUrl: "https://i.ytimg.com/vi/IwlMBvuDk5E/hqdefault.jpg",
    description:
      "An in-depth web development tutorial covering various aspects of building websites and web applications.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 2200000,
    likes: 35000,
    dislikes: 250,
    uploadDate: "2021-10-10",
    category: "Education",
    comments: [
      {
        username: "frontend_fan",
        userId: "user004",
        text: "I built my first website following this tutorial. Amazing content!",
        timestamp: "2021-10-11T09:00:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=IwlMBvuDk5E",
  },
  {
    videoId: "hKB-YGF14SY",
    title: "JavaScript Tutorial In Hindi",
    thumbnailUrl: "https://i.ytimg.com/vi/hKB-YGF14SY/hqdefault.jpg",
    description:
      "A comprehensive JavaScript tutorial in Hindi, covering basics to advanced topics.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 1750000,
    likes: 28000,
    dislikes: 180,
    uploadDate: "2021-09-05",
    category: "Education",
    comments: [
      {
        username: "js_learner",
        userId: "user005",
        text: "Best JavaScript tutorial I've found. Kudos!",
        timestamp: "2021-09-06T14:20:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=hKB-YGF14SY",
  },
  {
    videoId: "RGKi6LSPDLU",
    title: "React JS Tutorial for Beginners",
    thumbnailUrl: "https://i.ytimg.com/vi/RGKi6LSPDLU/hqdefault.jpg",
    description:
      "Learn React JS from scratch with this beginner-friendly tutorial.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 3000000,
    likes: 40000,
    dislikes: 300,
    uploadDate: "2021-08-15",
    category: "Education",
    comments: [
      {
        username: "react_rookie",
        userId: "user006",
        text: "React seemed tough until I watched this. Thanks a ton!",
        timestamp: "2021-08-16T09:30:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },

  {
    videoId: "TlB_eWDSMt4",
    title: "Node.js Tutorial for Beginners",
    thumbnailUrl: "https://i.ytimg.com/vi/TlB_eWDSMt4/hqdefault.jpg",
    description:
      "An introductory tutorial on Node.js, guiding viewers through server-side JavaScript development.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 3200000,
    likes: 38000,
    dislikes: 250,
    uploadDate: "2021-07-10",
    category: "Education",
    comments: [
      {
        username: "backend_guru",
        userId: "user007",
        text: "This tutorial gave me a great start in backend development. Thanks!",
        timestamp: "2021-07-11T10:00:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=TlB_eWDSMt4",
  },
  {
    videoId: "JxzZxdht-XY",
    title: "Django Tutorial In Hindi",
    thumbnailUrl: "https://i.ytimg.com/vi/JxzZxdht-XY/hqdefault.jpg",
    description:
      "A comprehensive Django tutorial in Hindi, covering web development with Python's Django framework.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 2800000,
    likes: 45000,
    dislikes: 180,
    uploadDate: "2021-06-05",
    category: "Education",
    comments: [
      {
        username: "python_webdev",
        userId: "user008",
        text: "Best Django tutorial in Hindi. Really helped me!",
        timestamp: "2021-06-06T14:30:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=JxzZxdht-XY",
  },
  {
    videoId: "GJoXy8cB3lo",
    title: "Machine Learning Tutorials Using Python In Hindi",
    thumbnailUrl: "https://i.ytimg.com/vi/_u-PaJCpwiU/hqdefault.jpg",
    description:
      "An introductory tutorial on machine learning concepts and applications using Python, presented in Hindi.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 1900000,
    likes: 32000,
    dislikes: 120,
    uploadDate: "2021-05-20",
    category: "Education",
    comments: [
      {
        username: "ml_beginner",
        userId: "user009",
        text: "Great explanation of ML concepts! Really helped me understand.",
        timestamp: "2021-05-21T12:00:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=_u-PaJCpwiU",
  },
  {
    videoId: "RBSGKlAvoiM",
    title: "Data Structures and Algorithms Tutorial In Hindi",
    thumbnailUrl: "https://i.ytimg.com/vi/RBSGKlAvoiM/hqdefault.jpg",
    description:
      "Learn about various data structures and algorithms with this detailed tutorial in Hindi.",
    subscriber: "7.13M",
    channelId: "UCeVMnSShP_Iviwkknt83cww",
    uploader: "mychannel",
    views: 2600000,
    likes: 41000,
    dislikes: 170,
    uploadDate: "2021-04-10",
    category: "Education",
    comments: [
      {
        username: "dsa_student",
        userId: "user010",
        text: "This DSA tutorial helped me clear my coding interview. Thanks!",
        timestamp: "2021-04-11T11:15:00Z",
      },
    ],
    videoLink: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
  },
];
